name: Atualizar Capas do Malscraper

on:
  schedule:
    - cron: '0 3 * * *' #
  workflow_dispatch:

jobs:
  update-covers:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Fazer Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script para gerar novas capas
        run: python generate_css.py

      - name: Gravar as Alterações no GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add capas.css
          git commit -m "chore: atualizar capas do malscraper (automático)" || echo "Nenhuma capa nova para atualizar."
          git push
